services:
  - type: web
    name: shopify-b2b-app
    env: node
    region: oregon
    plan: free
    # rootDir: .   <- SI EXISTE ESTA LÍNEA, BÓRRALA
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.20.5
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SCOPES
        value: read_products,write_products,read_customers,write_customers,read_orders,write_orders,read_price_rules,write_price_rules,read_discounts,write_discounts
      - key: SESSION_SECRET
        generateValue: true
      - key: HOST
        fromService:
          type: web
          name: shopify-b2b-app
          property: host
